@extends('layouts.print')
@section('title')
<div class="app-page-title">
    <div class="page-title-wrapper">
        <div class="page-title-heading">
            <div class="page-title-icon">
                <i class="fa fa-book icon-gradient bg-plum-plate">
                </i>
            </div>
        </div>
    </div>
</div>    
@endsection
@section('content')
<div class="row justify-content-center">
    <div class="col-lg-10">
        <div class="main-card mb-3 card">
            <div class="card-header">
                Task Report: {{ $user->name}}
            </div>
            <div class="card-body"><h5 class="card-title">Tasks Performed from {{Carbon\Carbon::parse($request_start)->format('H:i M d, Y')}} to {{Carbon\Carbon::parse($request_end)->format('H:i M d, Y')}}</h5>
                <div class="table-responsive">
                    <table class="mb-0 table text-center">
                        <thead>
                        <tr>
                            <th>Task Name</th>
                            <th>Description</th>
                            <th>Personnel</th>
                            <th>Resources</th>
                            <th>Deliverable</th>
                            <th>Start</th>
                            <th>End</th>
                            <th>Date Started</th>
                            <th>Date Ended</th>
                            <th>Duration</th>
                            <th>Status</th>
                        </tr>
                        </thead>
                        <tbody>
                            @foreach ($tasks as $task)
                            <tr>
                                <td><p>{!!$task->name!!}</p></td>
                                <td>{!!$task->description!!}</td>
                                <td><p>{!!implode(',<br>',$task->users()->get()->pluck('name')->toArray())!!}</p></td>
                                <td>{!!$task->resources!!}</td>
                                <td>{!!$task->deliverable!!}</td>
                                <td><p>{!!$task->start->format('H:i M d, Y')!!}</p></td>
                                <td><p>{!!$task->end->format('H:i M d, Y')!!}</p></td>
                                <td><p>{!!$task->started->format('H:i M d, Y')!!}</p></td>
                                @if(!empty($task->ended))
                                <td><p>{!!$task->ended->format('H:i M d, Y')!!}</p></td>
                                <td><p>
                                    @if ($task->ended->diffInMinutes($task->started)<60)
                                        {!!$task->ended->diffInMinutes($task->started)!!} mins
                                    @elseif($task->ended->diffInHours($task->started)<24)
                                        {!!$task->ended->diffInHours($task->started)!!} hours
                                    @elseif($task->ended->diffInDays($task->started)<1)
                                        {!!$task->ended->diffInDays($task->started)!!} day
                                    @elseif($task->ended->floatDiffInDays($task->started)>1)
                                        {!!sprintf("%.2f", $task->ended->floatDiffInDays($task->started))!!} days
                                    @endif
                                </p></td>
                                @else
                                <td></td>
                                <td></td>
                                @endif
                                
                                <td><p>
                                    @if($task->status=="2")
                                    Pending
                                    @elseif($task->status=="3")
                                    Approved
                                    @elseif($task->status=="4")
                                    In Progress
                                    @elseif($task->status=="5")
                                    Completed
                                    @endif
                                </p></td>

                            </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
            <div class="card-footer">
                Generated By: {{Auth::user()->name}} on {{Carbon\Carbon::now()->format('H:i M d, Y')}}
            </div>
        </div>
    </div>
</div>
@endsection